# device 
device: 'cuda:1'

# training params
epochs: 3 # number of epochs
batch_size: 512 # batch size to train with the buffer data
lr_rate: 0.0001 # learning rate
weight_decay: 0.00001 
r_exp: 1 # number of rounds of restricted exploration
f_exp: 1 # number of rounds of free exploration
max_length: 120 # max iteration number for each single instance
visualization: True # whether generate visualizations of the trajectories

# test
test: False # whether run test

# dirs
checkpoints_dir: './checkpoints/'
# docker 
docker_sub_dir: /graph_based_baselines/iCurb
docker_container_name: topo_iCurb
docker_port_number: 5011
